### ISSUE TITLE
Releases 1.2.4 and above reintroduce Issue #119 (translating messages originally written in "to" language)

### ISSUE THREAD

**Issue by carter-yagemann** [RitaBot-Project/RitaBot#423]
**Describe the bug**
Releases 1.2.2 and 1.2.3 contain a check in `translate.js` to ensure that messages already written in the desired "to" language will not be translated:

https://github.com/RitaBot-Project/RitaBot/blob/1963fdece5bed0ee74c268ca23e3926a480e615d/src/core/translate.js#L567-L572

This check was removed in releases 1.2.4 and above, reintroducing the bug. Why was this check removed? I cannot find a clear answer in the code comments or commit messages.

**To Reproduce**
1. `!tr channel from auto to english for #same_channel`
2. Send English message to channel.

**Expected behaviour**
Bot will detect that the message is already in the "to" language and not translate it.

**Comment by JShep89** [comment]
Short story it was requested by a couple of our user's, plan was to put it back in but it keeps getting pushed due to more pressing issues. But rest assured we will be re-adding it as soon as possible

**Comment by ArtanisTheOne** [comment]
The reason it was removed was because it was causing issues with peoples' conversations. The detection is not the best and would sometimes ignore a random word which isnt the same, there is also the fact that in translation channels (not same channel) people would want messages sent, no matter the language, to be conveyed to the other channel.

**Comment by ZyC0R3** [comment]
Things like, 
umm, grr, hm, duu, ah
Trigger transaltions when they are not supposed too

**Comment by ZyC0R3** [comment]
Should now be Fixed.
