### ISSUE TITLE
Suggestion: Cultural Sensitivity

### ISSUE THREAD

**Issue by toitzi** [RitaBot-Project/RitaBot#482]
**Very Important Note / Disclaimer**: I do not want to start a discussion on Cultural Sensitivity here, or wether if it has to do with tech terms or so on. Feel free to close this if not relevant to you.

As you all probably know, github has renamed some of the terms they use (e.g rename `master` to `main`) - see [here](https://github.com/github/renaming) , other companies did the same, also with lots of other terms like `master/slave`.

I saw RitaBot still uses the terms "blacklist" and (in the more recent dev version): "whitelist".
My suggestion is renaming them to something like "blocklist" and "allowlist" or similiar.

I think it may be as simple as search and replace, but i am not sure if that would break backwards compatibility, altough i think it is worth looking into.

**Comment by JShep89** [comment]
this is technology and has nothing to do with culture or race and I would appreciate it if you would neglect trying to turn it into such.

**Comment by ZyC0R3** [comment]
Hi. Thank you for taking time to raising your concerns. 

I agree with the statement made by jshep in relation to this. This is not the place for cultural related conversation. The terms you are referring to, while are seen by a segment of the wider population as inappropriate, are contextually correct in the terms they are used here. 

For logistics reason we are not able to change master to main at this time. It is something we are working towards as will be a requirement for GitHub in the next few years. 

As for whitelist/ed and blacklist/ed, historically they have never had any associations with culture or race. 

The term blacklist was first cited in the early 1600s to describe a list of those who were under suspicion and thus not to be trusted. Even earlier blacklist (n.) also black-list, "list of persons who have incurred suspicion, earned punishment, or are for any reason deemed objectionable by the makers and users of the list," 1610s, from black (adj.), here indicative of disgrace, censure, punishment (a sense attested from 1590s, in black book)

And further historical evidence can be seen in The state papers of Charles II saying "If any innocent soul be found in this black list, let him not be offended at me, but consider whether some mistaken principle or interest may not have misled him to vote"

Whitelist was a direct opposite derivative in old English. A book of white and in Holly nature shall be trusted by king, country and peasants alike. It will be honoured by knights, nobles and all folk bound by law. This was because religious books, and books of nobility, lineage and law were bound in white leather. The hardest colour to dye leather in those times. 

Further to your points of culture this has been widely disputed in many notable publication. The most common referred to (and yes I was lazy and looked on wiki) is "Those that oppose these changes question its attribution to race, citing the same etymology quote that the 2018 journal uses. The quote suggests that the term 'blacklist' arose from 'black book' almost 100 years prior. 'Black book' does not appear to have any etymology or sources that support ties to race, instead coming from the 1400s referring "to a list of people who had committed crimes or fallen out of favor with leaders" and popularized by King Henry VIII's literal usage of a book bound in black.

Modern criticism of these terms has no tie with the associated link and purpose they are used for in fraud, Finance, technology or other establishments that use it to identify bad actors. 

We use the term blacklist to denote servers that maliciously use Rita, her services, breach discord T&C or/and prevent other users from using her. 

We use the term whitelisted to denote a server that is immune to moderation actions or is protected as a test server where we develop Rita and her functions. 

Discord itself has no way to identify a users race, ethnic background, religious background or sexual orientation that is publicly available to any developers so we have no way of using these terms for that purpose. And I can see you have not suggested they are using in that way but it's a fine line between curiosity and accusation. Please consider this matter closed. If you want to discuss it further please reach out to a Dev directly on discord and we will be happy to talk about any concerns you may have. 

As a precaution and to ensure we have meet all legal requirements I will reach out to discord to ensure there is no restrictions on these terms in there development environment. If they should advise otherwise we will make any relevant changes to be compliant.

**Comment by ZyC0R3** [comment]
Sidenote. 

A yellowlist was a list of know war criminals or smugglers
A pinklist was a list of ladies of the night 
And a redlist was a list animals or species seen to be endangered. 

These colours can also be substituted to a race, culture or sexual orientation but are not as given the same level as dispute as the aforementioned terms

**Comment by JShep89** [comment]
![image](https://user-images.githubusercontent.com/46389911/142300915-995f5730-0c9d-4159-8ce2-8a59af45d15b.png)
uh oh looks like someone is not a believer of practicing what they preach!!
