### ISSUE TITLE
Hindi translation

### ISSUE THREAD

**Issue by JShep89** [RitaBot-Project/RitaBot#485]
Hindi won't translate to any other languages

**Comment by cyberlooper** [comment]
I did a little investigation into this.

'!tr this from hindi to english: मेरी घड़ी में कुछ गड़बड़ है' = It works fine.
'!tr this from hindi to french: मेरी घड़ी में कुछ गड़बड़ है' = It works fine.
'!tr this from hindi to german: मेरी घड़ी में कुछ गड़बड़ है' = It works fine.

'!tr this from german to hindi: Etwas stimmt nicht mit meiner Uhr = It works fine.
'!tr from french to hindi: Quelque chose ne va pas avec ma montre' = It works fine.
'!tr this from hindi to english:मेरी घड़ी में कुछ गड़बड़ है' = It works fine.

Reacting to the engish text 'There is something wrong with my watch' with Flag_IN = It works fine.

Reacting with flag_gb, flag_us, flag_fr to the hindi text मेरी घड़ी में कुछ गड़बड़ है = It works fine.

Conclusion?

Either:
A. The bug is only present in the current stable version out of the master branch.
or
B. This was inadvertently fixed during the writing of test-branch using DJSv13.

**Comment by JShep89** [comment]
I tested it again using the official bot and it seems to be working again. I can only speculate but i believe that the problem was on google end
