### ISSUE TITLE
Re-translate text when edited

### ISSUE THREAD

**Issue by wdaniel1985** [RitaBot-Project/RitaBot#99]
**Is your feature request related to a problem? Please describe.**
Currently, an edited message is not translated to the other channels again. When a typo is detected immediately after sending, a correction and re-translation would add a benefit. 

**Describe the solution you'd like**
It should be possible to edit the channels for a certain amount of time, like 10 minutes after the message is translated. 
It would require an additional table to store the message-ID and the translated message-ID's (with channel id and language, timestamp). When editing is detected, the re-translation should be feasible. 

**Additional context**
Recommended steps:
Step 1: Testing how editing is possible across channels with a simple ping pong edit example
Step 2: Add a database table with the required fields. Store the messages in the table. 
Step 3: Implement some periodically checking task (keyword Timeout) to check for older messages and delete these
Step 4: Implement retranslation on message edit

**Comment by timbas-488** [comment]
Could removal of deleted message translation be handled in the same way?

**Comment by ArtanisTheOne** [comment]
> Could removal of deleted message translation be handled in the same way?

Yes, that would be included in re-translating text if edited

**Comment by src-r-r** [comment]
I've been taking a whack at it and so far it's sounding more complicated that I envisioned. I've pretty much come up with a solution, but it's ugly.

_(full disclosure: I'm pretty new to discord & discord development, though I have a strong js background)_

The issue is that the translation is an EmbedMessages instance which are not easily fetchable (because they're embedded within a Message). So we'll need to actively attach the parent message ID of the EmbeddedMessage to the original Message so that when an edit occurs, we can fetch the EmbeddedMessage and update it.

I'm at the point where the program flow can detect when an update occurs. I just need to do the back&forth referencing, which I estimate will take another hour or 2. If someone else whats to take a whack at it (or come up with a better solution), feel free. If so I'd suggest starting work in the `run` function of `update.auto.js`

Here's the branch I'm working on: https://github.com/src-r-r/RitaBot/tree/srcrr-2021WW20-feature-99-update-translation-on-message-edit.

**Comment by ArtanisTheOne** [comment]
Very nice, yeah

The issue isnt due to it being an embed, more due to an eddited message's ID will not be the same as the translated message ID's. So only way to make this work would be to store all translation message IDs and author message IDs and check them when a message is edited ( if edited message id is in this array then look in the arrays object for all its translations ). An array of ALL messages ever sent with each key being message id would need to be made, among other things

**Comment by ArtanisTheOne** [comment]
I noticed you push to an array in data, lemme just help you know the structure (it was so annoying to understand when I started)

`data` is the var used in all these files which has everything we would want

Bot startup process goes like (bot.js ---(call to events.js)> events.js ----> each events thing to do and then everything is loaded)

When a message is sent event triggers in event.js and goes to message.js, the `data` variable is then rewritten with the info for that message

`data` is rewritten for every message, reaction, translation so for any data you would want to store for when its edited it would need to be in another variable which is exportable and wont be rewritten

**Comment by ArtanisTheOne** [comment]
Or you could do it as you are doing it and only support last 100 messages by fetching then checking each
